apiVersion: v1
kind: ConfigMap

metadata:
  name: msvc-users

data:
  port: "8001"
  db_host: mysql9:3306
  database: msvc_users
  username: root
  #password: Rig0bert0.
---
##Asi se puede tener varias configuraciones en un solo archivo
apiVersion: v1
kind: ConfigMap

metadata:
  name: msvc-courses

data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_courses
  username: postgres
  #password: Rig0bert0.