apiVersion: apps/v1
kind: Deployment

metadata:
  name: msvc-courses

spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-courses
  template:
    metadata:
  #    name: courses   el nombrte del template no es necesario
      labels:
        app: msvc-courses
    spec:
      containers:
        - name: msvc-courses
          image: rignu/udemy-courses:latest
          ports:
            - containerPort: 8002
              protocol: TCP

      